name: note_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version info
version: 1.0.0+1

# Dart SDK environment
environment:
  sdk: ^3.7.2

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Assets (e.g., fonts, images)
  assets:
    - assets/fonts/IndieFlower-Regular.ttf

  # Custom fonts
  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
